name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.402
    - name: Install dependencies
      run: dotnet restore "src/WebApp/WebApplicationAPI.csproj"
    - name: Build
      run: dotnet build "src/WebApp/WebApplicationAPI.csproj" --configuration Release --no-restore
    - name: Test
      run: dotnet test "tests/IntegrationTests/IntegrationTests.csproj" --configuration Release --no-restore --verbosity normal
